version: '3.4'
x-db-variables: &db-variables
  MYSQL_DATABASE: 'CS4230'
  MYSOL_USER: 'cs4230-user'
  MYSQL_PASSWORD: 'password'
  MYSQL_PORT:
services:
#  hw2:
#    build: .
#    ports:
#      - 8080:8080
#    environment:
#      MYSQL_URL: mysql
#      <<: *db-variables
#    depends_on:
#      - mysql
#    volumes:
#      - ./target/:/usr/local/tomcat/webapps
  mysql:
    image: mysql:8.0.26
    #Needed for my processor
    platform: linux/x86_64
    volumes:
      - cs4230-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
       MYSQL_DATABASE: 'CS4230'
       MYSOL_USER: 'cs4230-user'
       MYSQL_PASSWORD: 'password'
#      <<: *db-variables
       MYSQL_ROOT_PASSWORD: 'password'
volumes: 
  cs4230-db: