version: '3.4'
x-db-variables: &db-variables
  MYSQL_DATABASE: 'CS4230'
  MYSOL_USER: 'cs4230-user'
  MYSQL_PASSWORD: 'password'
  MYSQL_PORT:
services:
  homework:
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_URL: mysql
      <<: *db-variables
    depends_on:
      - mysql
    volumes:
      - •/target/:/usr/local/tomcat/webapps
  mysql:
    image: mysql:8.0.20
    volumes:
      - cs4230-db:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      <<: *db-variables
      MYSQL_ROOT_PASSWORD: 'password'
volumes: 
  cs4230-db: