CREATE TABLE CONTACT(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE ADDRESS(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CONTACT_ID INT NOT NULL,
    ADDRESS_TYPE varchar(50) NOT NULL,
    ADDRESS1 varchar(256) NOT NULL,
    ADDRESS2 varchar(256),
    CITY varchar(256) NOT NULL,
    STATE varchar(256) NOT NULL,
    ZIPCODE varchar(20) NOT NULL,
    FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID)
) ENGINE=INNODB;